### ISSUE TITLE
Why filter "Beaver.MLIR.Dialect.*"  when generating docs?

### ISSUE THREAD

**Issue by guitcastro** [beaver-lodge/beaver#220]
Pretty much the title, I want to try I few things in Beaver I a find out that generated dialect codes does not have docs.

I think would be really helpful if they had, for IDE auto complete and etc

**Comment by jackalcooper** [comment]
hi @guitcastro , thanks for trying it out. To answer you questions
- because they are so many and will make the documentation generated not readable
- usually the MLIR official site's dialects docs are more informative  https://mlir.llvm.org/docs/Dialects/
- IDE/LSP has no problem picking up these functions for MLIR ops
<img width="536" alt="image" src="https://github.com/beaver-lodge/beaver/assets/5133557/da44f80c-bc05-480b-9dbe-53e510697667">
